# Generated by Django 4.0.4 on 2022-04-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperCollectionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField(default=0)),
                ('last_collection', models.DateTimeField()),
                ('name', models.CharField(max_length=120)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alternative_solution.bin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarbageCollectionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField(default=0)),
                ('last_collection', models.DateTimeField()),
                ('name', models.CharField(max_length=120)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alternative_solution.bin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
