# Generated by Django 4.0.4 on 2022-04-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternative_solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagecollectionoperation',
            name='bin',
        ),
        migrations.AddField(
            model_name='garbagecollectionoperation',
            name='bin',
            field=models.ManyToManyField(to='alternative_solution.bin'),
        ),
        migrations.RemoveField(
            model_name='papercollectionoperation',
            name='bin',
        ),
        migrations.AddField(
            model_name='papercollectionoperation',
            name='bin',
            field=models.ManyToManyField(to='alternative_solution.bin'),
        ),
    ]
